/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DailyMetrics {
    date: string;
    calories: number;
    steps: bigint;
}
export interface MealLog {
    date: string;
    portionSize: string;
    estimatedCalories: number;
    mealName: string;
}
export type WorkoutSplit = {
    __kind__: "pushPullLegs";
    pushPullLegs: null;
} | {
    __kind__: "upperLower";
    upperLower: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "fullBody";
    fullBody: null;
} | {
    __kind__: "broSplit";
    broSplit: null;
};
export interface Workout {
    weight: number;
    duration: number;
    date: string;
    reps: number;
    sets: number;
    exercise: string;
    muscleGroup: string;
}
export interface UserProfile {
    height?: number;
    fitnessGoal: FitnessGoal;
    preferredCurrency: string;
    goalWeight?: number;
    bodyWeight?: number;
    profession?: string;
    workoutSplit?: WorkoutSplit;
    income?: number;
}
export interface Transaction {
    date: string;
    description: string;
    category: Variant_saving_other_investment_needs;
    amount: number;
}
export enum FitnessGoal {
    cut = "cut",
    bulk = "bulk"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_saving_other_investment_needs {
    saving = "saving",
    other = "other",
    investment = "investment",
    needs = "needs"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyMetrics(): Promise<Array<DailyMetrics>>;
    getMealLogs(): Promise<Array<MealLog>>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkouts(): Promise<Array<Workout>>;
    isCallerAdmin(): Promise<boolean>;
    logDailyMetrics(metrics: DailyMetrics): Promise<void>;
    logMeal(mealLog: MealLog): Promise<void>;
    logTransaction(transaction: Transaction): Promise<void>;
    logWorkout(workout: Workout): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateFinanceProfile(income: number | null, profession: string | null): Promise<void>;
    updateFitnessGoal(goal: FitnessGoal): Promise<void>;
    updateFitnessProfile(bodyWeight: number | null, height: number | null, goalWeight: number | null, workoutSplit: WorkoutSplit | null): Promise<void>;
}
import type { FitnessGoal as _FitnessGoal, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole, WorkoutSplit as _WorkoutSplit } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyMetrics(): Promise<Array<DailyMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyMetrics();
            return result;
        }
    }
    async getMealLogs(): Promise<Array<MealLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealLogs();
            return result;
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkouts(): Promise<Array<Workout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkouts();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logDailyMetrics(arg0: DailyMetrics): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDailyMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDailyMetrics(arg0);
            return result;
        }
    }
    async logMeal(arg0: MealLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logMeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMeal(arg0);
            return result;
        }
    }
    async logTransaction(arg0: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logTransaction(to_candid_Transaction_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logTransaction(to_candid_Transaction_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async logWorkout(arg0: Workout): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkout(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFinanceProfile(arg0: number | null, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFinanceProfile(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFinanceProfile(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFitnessGoal(arg0: FitnessGoal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFitnessGoal(to_candid_FitnessGoal_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFitnessGoal(to_candid_FitnessGoal_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFitnessProfile(arg0: number | null, arg1: number | null, arg2: number | null, arg3: WorkoutSplit | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFitnessProfile(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFitnessProfile(to_candid_opt_n28(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_FitnessGoal_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessGoal): FitnessGoal {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutSplit_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutSplit): WorkoutSplit {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutSplit]): WorkoutSplit | null {
    return value.length === 0 ? null : from_candid_WorkoutSplit_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    description: string;
    category: {
        saving: null;
    } | {
        other: null;
    } | {
        investment: null;
    } | {
        needs: null;
    };
    amount: number;
}): {
    date: string;
    description: string;
    category: Variant_saving_other_investment_needs;
    amount: number;
} {
    return {
        date: value.date,
        description: value.description,
        category: from_candid_variant_n18(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    height: [] | [number];
    fitnessGoal: _FitnessGoal;
    preferredCurrency: string;
    goalWeight: [] | [number];
    bodyWeight: [] | [number];
    profession: [] | [string];
    workoutSplit: [] | [_WorkoutSplit];
    income: [] | [number];
}): {
    height?: number;
    fitnessGoal: FitnessGoal;
    preferredCurrency: string;
    goalWeight?: number;
    bodyWeight?: number;
    profession?: string;
    workoutSplit?: WorkoutSplit;
    income?: number;
} {
    return {
        height: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.height)),
        fitnessGoal: from_candid_FitnessGoal_n7(_uploadFile, _downloadFile, value.fitnessGoal),
        preferredCurrency: value.preferredCurrency,
        goalWeight: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.goalWeight)),
        bodyWeight: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.bodyWeight)),
        profession: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.profession)),
        workoutSplit: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.workoutSplit)),
        income: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.income))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pushPullLegs: null;
} | {
    upperLower: null;
} | {
    custom: string;
} | {
    fullBody: null;
} | {
    broSplit: null;
}): {
    __kind__: "pushPullLegs";
    pushPullLegs: null;
} | {
    __kind__: "upperLower";
    upperLower: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "fullBody";
    fullBody: null;
} | {
    __kind__: "broSplit";
    broSplit: null;
} {
    return "pushPullLegs" in value ? {
        __kind__: "pushPullLegs",
        pushPullLegs: value.pushPullLegs
    } : "upperLower" in value ? {
        __kind__: "upperLower",
        upperLower: value.upperLower
    } : "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "fullBody" in value ? {
        __kind__: "fullBody",
        fullBody: value.fullBody
    } : "broSplit" in value ? {
        __kind__: "broSplit",
        broSplit: value.broSplit
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    saving: null;
} | {
    other: null;
} | {
    investment: null;
} | {
    needs: null;
}): Variant_saving_other_investment_needs {
    return "saving" in value ? Variant_saving_other_investment_needs.saving : "other" in value ? Variant_saving_other_investment_needs.other : "investment" in value ? Variant_saving_other_investment_needs.investment : "needs" in value ? Variant_saving_other_investment_needs.needs : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cut: null;
} | {
    bulk: null;
}): FitnessGoal {
    return "cut" in value ? FitnessGoal.cut : "bulk" in value ? FitnessGoal.bulk : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n16(_uploadFile, _downloadFile, x));
}
function to_candid_FitnessGoal_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): _FitnessGoal {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutSplit_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutSplit): _WorkoutSplit {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutSplit | null): [] | [_WorkoutSplit] {
    return value === null ? candid_none() : candid_some(to_candid_WorkoutSplit_n26(_uploadFile, _downloadFile, value));
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    description: string;
    category: Variant_saving_other_investment_needs;
    amount: number;
}): {
    date: string;
    description: string;
    category: {
        saving: null;
    } | {
        other: null;
    } | {
        investment: null;
    } | {
        needs: null;
    };
    amount: number;
} {
    return {
        date: value.date,
        description: value.description,
        category: to_candid_variant_n21(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    height?: number;
    fitnessGoal: FitnessGoal;
    preferredCurrency: string;
    goalWeight?: number;
    bodyWeight?: number;
    profession?: string;
    workoutSplit?: WorkoutSplit;
    income?: number;
}): {
    height: [] | [number];
    fitnessGoal: _FitnessGoal;
    preferredCurrency: string;
    goalWeight: [] | [number];
    bodyWeight: [] | [number];
    profession: [] | [string];
    workoutSplit: [] | [_WorkoutSplit];
    income: [] | [number];
} {
    return {
        height: value.height ? candid_some(value.height) : candid_none(),
        fitnessGoal: to_candid_FitnessGoal_n24(_uploadFile, _downloadFile, value.fitnessGoal),
        preferredCurrency: value.preferredCurrency,
        goalWeight: value.goalWeight ? candid_some(value.goalWeight) : candid_none(),
        bodyWeight: value.bodyWeight ? candid_some(value.bodyWeight) : candid_none(),
        profession: value.profession ? candid_some(value.profession) : candid_none(),
        workoutSplit: value.workoutSplit ? candid_some(to_candid_WorkoutSplit_n26(_uploadFile, _downloadFile, value.workoutSplit)) : candid_none(),
        income: value.income ? candid_some(value.income) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_saving_other_investment_needs): {
    saving: null;
} | {
    other: null;
} | {
    investment: null;
} | {
    needs: null;
} {
    return value == Variant_saving_other_investment_needs.saving ? {
        saving: null
    } : value == Variant_saving_other_investment_needs.other ? {
        other: null
    } : value == Variant_saving_other_investment_needs.investment ? {
        investment: null
    } : value == Variant_saving_other_investment_needs.needs ? {
        needs: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): {
    cut: null;
} | {
    bulk: null;
} {
    return value == FitnessGoal.cut ? {
        cut: null
    } : value == FitnessGoal.bulk ? {
        bulk: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "pushPullLegs";
    pushPullLegs: null;
} | {
    __kind__: "upperLower";
    upperLower: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "fullBody";
    fullBody: null;
} | {
    __kind__: "broSplit";
    broSplit: null;
}): {
    pushPullLegs: null;
} | {
    upperLower: null;
} | {
    custom: string;
} | {
    fullBody: null;
} | {
    broSplit: null;
} {
    return value.__kind__ === "pushPullLegs" ? {
        pushPullLegs: value.pushPullLegs
    } : value.__kind__ === "upperLower" ? {
        upperLower: value.upperLower
    } : value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "fullBody" ? {
        fullBody: value.fullBody
    } : value.__kind__ === "broSplit" ? {
        broSplit: value.broSplit
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
