/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FitnessGoal = IDL.Variant({ 'cut' : IDL.Null, 'bulk' : IDL.Null });
export const WorkoutSplit = IDL.Variant({
  'pushPullLegs' : IDL.Null,
  'upperLower' : IDL.Null,
  'custom' : IDL.Text,
  'fullBody' : IDL.Null,
  'broSplit' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'height' : IDL.Opt(IDL.Float64),
  'fitnessGoal' : FitnessGoal,
  'preferredCurrency' : IDL.Text,
  'goalWeight' : IDL.Opt(IDL.Float64),
  'bodyWeight' : IDL.Opt(IDL.Float64),
  'profession' : IDL.Opt(IDL.Text),
  'workoutSplit' : IDL.Opt(WorkoutSplit),
  'income' : IDL.Opt(IDL.Float64),
});
export const DailyMetrics = IDL.Record({
  'date' : IDL.Text,
  'calories' : IDL.Nat16,
  'steps' : IDL.Nat,
});
export const MealLog = IDL.Record({
  'date' : IDL.Text,
  'portionSize' : IDL.Text,
  'estimatedCalories' : IDL.Nat16,
  'mealName' : IDL.Text,
});
export const Transaction = IDL.Record({
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Variant({
    'saving' : IDL.Null,
    'other' : IDL.Null,
    'investment' : IDL.Null,
    'needs' : IDL.Null,
  }),
  'amount' : IDL.Float64,
});
export const Workout = IDL.Record({
  'weight' : IDL.Float64,
  'duration' : IDL.Nat16,
  'date' : IDL.Text,
  'reps' : IDL.Nat8,
  'sets' : IDL.Nat8,
  'exercise' : IDL.Text,
  'muscleGroup' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyMetrics' : IDL.Func([], [IDL.Vec(DailyMetrics)], ['query']),
  'getMealLogs' : IDL.Func([], [IDL.Vec(MealLog)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logDailyMetrics' : IDL.Func([DailyMetrics], [], []),
  'logMeal' : IDL.Func([MealLog], [], []),
  'logTransaction' : IDL.Func([Transaction], [], []),
  'logWorkout' : IDL.Func([Workout], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFinanceProfile' : IDL.Func(
      [IDL.Opt(IDL.Float64), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateFitnessGoal' : IDL.Func([FitnessGoal], [], []),
  'updateFitnessProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(WorkoutSplit),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FitnessGoal = IDL.Variant({ 'cut' : IDL.Null, 'bulk' : IDL.Null });
  const WorkoutSplit = IDL.Variant({
    'pushPullLegs' : IDL.Null,
    'upperLower' : IDL.Null,
    'custom' : IDL.Text,
    'fullBody' : IDL.Null,
    'broSplit' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'height' : IDL.Opt(IDL.Float64),
    'fitnessGoal' : FitnessGoal,
    'preferredCurrency' : IDL.Text,
    'goalWeight' : IDL.Opt(IDL.Float64),
    'bodyWeight' : IDL.Opt(IDL.Float64),
    'profession' : IDL.Opt(IDL.Text),
    'workoutSplit' : IDL.Opt(WorkoutSplit),
    'income' : IDL.Opt(IDL.Float64),
  });
  const DailyMetrics = IDL.Record({
    'date' : IDL.Text,
    'calories' : IDL.Nat16,
    'steps' : IDL.Nat,
  });
  const MealLog = IDL.Record({
    'date' : IDL.Text,
    'portionSize' : IDL.Text,
    'estimatedCalories' : IDL.Nat16,
    'mealName' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Variant({
      'saving' : IDL.Null,
      'other' : IDL.Null,
      'investment' : IDL.Null,
      'needs' : IDL.Null,
    }),
    'amount' : IDL.Float64,
  });
  const Workout = IDL.Record({
    'weight' : IDL.Float64,
    'duration' : IDL.Nat16,
    'date' : IDL.Text,
    'reps' : IDL.Nat8,
    'sets' : IDL.Nat8,
    'exercise' : IDL.Text,
    'muscleGroup' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyMetrics' : IDL.Func([], [IDL.Vec(DailyMetrics)], ['query']),
    'getMealLogs' : IDL.Func([], [IDL.Vec(MealLog)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logDailyMetrics' : IDL.Func([DailyMetrics], [], []),
    'logMeal' : IDL.Func([MealLog], [], []),
    'logTransaction' : IDL.Func([Transaction], [], []),
    'logWorkout' : IDL.Func([Workout], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFinanceProfile' : IDL.Func(
        [IDL.Opt(IDL.Float64), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateFitnessGoal' : IDL.Func([FitnessGoal], [], []),
    'updateFitnessProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(WorkoutSplit),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };