/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyMetrics {
  'date' : string,
  'calories' : number,
  'steps' : bigint,
}
export interface MealLog {
  'date' : string,
  'portionSize' : string,
  'estimatedCalories' : number,
  'mealName' : string,
}
export interface Transaction {
  'date' : string,
  'description' : string,
  'category' : { 'saving' : null } |
    { 'other' : null } |
    { 'investment' : null } |
    { 'needs' : null },
  'amount' : number,
}
export interface UserProfile {
  'height' : [] | [number],
  'fitnessGoal' : { 'cut' : null } |
    { 'bulk' : null },
  'preferredCurrency' : string,
  'goalWeight' : [] | [number],
  'bodyWeight' : [] | [number],
  'profession' : [] | [string],
  'income' : [] | [number],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Workout {
  'weight' : number,
  'duration' : number,
  'date' : string,
  'reps' : number,
  'sets' : number,
  'exercise' : string,
  'muscleGroup' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyMetrics' : ActorMethod<[], Array<DailyMetrics>>,
  'getMealLogs' : ActorMethod<[], Array<MealLog>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkouts' : ActorMethod<[], Array<Workout>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logDailyMetrics' : ActorMethod<[DailyMetrics], undefined>,
  'logMeal' : ActorMethod<[MealLog], undefined>,
  'logTransaction' : ActorMethod<[Transaction], undefined>,
  'logWorkout' : ActorMethod<[Workout], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFinanceProfile' : ActorMethod<
    [[] | [number], [] | [string]],
    undefined
  >,
  'updateFitnessProfile' : ActorMethod<
    [[] | [number], [] | [number], [] | [number]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];